src/Entity/Contribution.php
<?php

namespace App\Entity;

use App\Utils\UploaderHelper;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ContributionRepository")
 */
class Contribution
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $feedbackedAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $publishedAt;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="contributions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="reviewableContributions")
     */
    private $approvedBy;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Term", inversedBy="contributions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $term;

    /**
     * @ORM\Column(type="datetime")
     */
    private $agreedTermsAt;

    /**
     * @var string
     * @ORM\Column(type="string", length=255)
     */
    private $documentFilename;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ContributionImage", mappedBy="contribution", orphanRemoval=true, cascade={"persist"})
     */
    private $contributionImages;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $approvedAt;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $feedback;

    public function __construct()
    {
        $this->contributionImages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getFeedbackedAt(): ?\DateTimeInterface
    {
        return $this->feedbackedAt;
    }

    public function setFeedbackedAt(?\DateTimeInterface $feedbackedAt): self //for fixture purpose
    {
        $this->feedbackedAt = $feedbackedAt;

        return $this;
    }

    public function registerFirstFeedbackTime(): self
    {
        $this->feedbackedAt = new \DateTime();

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeInterface
    {
        return $this->publishedAt;
    }

    public function setPublishedAt(?\DateTimeInterface $publishedAt): self //for fixture purpose
    {
        $this->publishedAt = $publishedAt;

        return $this;
    }

    public function publish(): self
    {
        $this->publishedAt = new \DateTime();

        return $this;
    }

    public function approve(): self
    {
        $this->approvedAt = new \DateTime();

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getApprovedBy(): ?User
    {
        return $this->approvedBy;
    }

    public function setApprovedBy(?User $approvedBy): self
    {
        $this->approvedBy = $approvedBy;

        return $this;
    }

    public function getTerm(): ?Term
    {
        return $this->term;
    }

    public function setTerm(?Term $term): self
    {
        $this->term = $term;

        return $this;
    }

    public function getAgreedTermsAt(): ?\DateTimeInterface
    {
        return $this->agreedTermsAt;
    }

    public function setAgreedTermsAt(?\DateTimeInterface $agreeTermsAt): self //for fixture purpose
    {
        $this->agreedTermsAt = $agreeTermsAt;

        return $this;
    }

    public function agreeToTerms()
    {
        $this->agreedTermsAt = new \DateTime();
    }

    public function getDocumentFilename(): ?string
    {
        return $this->documentFilename;
    }

    public function setDocumentFilename(string $documentFilename): self
    {
        $this->documentFilename = $documentFilename;

        return $this;
    }

    public function getDocumentPath()
    {
        return UploaderHelper::CONTRIBUTION_DOCUMENT.'/'.$this->getDocumentFilename();
    }

    /**
     * @return Collection|ContributionImage[]
     */
    public function getContributionImages(): Collection
    {
        return $this->contributionImages;
    }

    public function addContributionImage(ContributionImage $contributionImage): self
    {
        if (!$this->contributionImages->contains($contributionImage)) {
            $this->contributionImages[] = $contributionImage;
        }

        return $this;
    }

    public function removeContributionImage(ContributionImage $contributionImage): self
    {
        if ($this->contributionImages->contains($contributionImage)) {
            $this->contributionImages->removeElement($contributionImage);
            // set the owning side to null (unless already changed)
            if ($contributionImage->getContribution() === $this) {
            }
        }

        return $this;
    }

    public function getApprovedAt(): ?\DateTimeInterface
    {
        return $this->approvedAt;
    }

    public function setApprovedAt(?\DateTimeInterface $approvedAt): self
    {
        $this->approvedAt = $approvedAt;

        return $this;
    }

    public function getFeedback(): ?string
    {
        return $this->feedback;
    }

    public function setFeedback(?string $feedback): self
    {
        $this->feedback = $feedback;

        return $this;
    }

    public function isAfter14days()
    {
        return $this->agreedTermsAt < new \DateTimeImmutable('-14 days');
    }
}

src/Entity/ContributionImage.php
<?php

namespace App\Entity;

use App\Utils\UploaderHelper;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ContributionImageRepository")
 */
class ContributionImage
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $filename;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $originalFilename;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $mimeType;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Contribution", inversedBy="contributionImages", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $contribution;

    /**
     * ContributionImage constructor.
     *
     * @param Contribution $contribution
     */
    public function __construct(Contribution $contribution)
    {
        $this->contribution = $contribution;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFilename(): ?string
    {
        return $this->filename;
    }

    public function setFilename(string $filename): self
    {
        $this->filename = $filename;

        return $this;
    }

    public function getOriginalFilename(): ?string
    {
        return $this->originalFilename;
    }

    public function setOriginalFilename(string $originalFilename): self
    {
        $this->originalFilename = $originalFilename;

        return $this;
    }

    public function getMimeType(): ?string
    {
        return $this->mimeType;
    }

    public function setMimeType(string $mimeType): self
    {
        $this->mimeType = $mimeType;

        return $this;
    }

    public function getContribution(): ?Contribution
    {
        return $this->contribution;
    }

    public function getImagePath()
    {
        return UploaderHelper::CONTRIBUTION_IMAGE.'/'.$this->getFilename();
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface
{
    const ROLE_ADMIN = 'ROLE_ADMIN';
    const ROLE_MANAGER = 'ROLE_MANAGER';
    const ROLE_COORDINATOR = 'ROLE_COORDINATOR';
    const ROLE_STUDENT = 'ROLE_STUDENT';
    const ROLE_GUEST = 'ROLE_GUEST';

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @var string
     */
    private $plainPassword;

    /**
     * @var bool
     * @ORM\Column(type="boolean")
     */
    private $enabled;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lastName;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Faculty", inversedBy="users")
     */
    private $faculty;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Contribution", mappedBy="author", orphanRemoval=true)
     */
    private $contributions;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Contribution", mappedBy="coordinator")
     */
    private $reviewableContributions;

    public function __construct()
    {
        $this->contributions = new ArrayCollection();
        $this->reviewableContributions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        $this->plainPassword = null;
    }

    /**
     * @return string
     */
    public function getPlainPassword(): ?string
    {
        return $this->plainPassword;
    }

    /**
     * @param string $plainPassword
     */
    public function setPlainPassword(?string $plainPassword): void
    {
        $this->plainPassword = $plainPassword;
    }

    /**
     * @return bool
     */
    public function isEnabled(): bool
    {
        return $this->enabled;
    }

    /**
     * @param bool $enabled
     */
    public function setEnabled(bool $enabled): void
    {
        $this->enabled = $enabled;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(?string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(?string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getDisplayName(): string
    {
        return (!$this->firstName && !$this->lastName) ? $this->email : "$this->firstName $this->lastName";
    }

    public function getFaculty(): ?Faculty
    {
        return $this->faculty;
    }

    public function setFaculty(?Faculty $faculty): self
    {
        $this->faculty = $faculty;

        return $this;
    }

    public function getShortRole(): string
    {
        return mb_strtolower(str_replace('ROLE_', '', $this->roles[0]));
    }

    public function getLongRole(): string
    {
        return $this->roles[0];
    }

    /**
     * @return Collection|Contribution[]
     */
    public function getContributions(): Collection
    {
        return $this->contributions;
    }

    public function addContribution(Contribution $contribution): self
    {
        if (!$this->contributions->contains($contribution)) {
            $this->contributions[] = $contribution;
            $contribution->setAuthor($this);
        }

        return $this;
    }

    public function removeContribution(Contribution $contribution): self
    {
        if ($this->contributions->contains($contribution)) {
            $this->contributions->removeElement($contribution);
            // set the owning side to null (unless already changed)
            if ($contribution->getAuthor() === $this) {
                $contribution->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Contribution[]
     */
    public function getReviewableContributions(): Collection
    {
        return $this->reviewableContributions;
    }

    public function addReviewableContribution(Contribution $reviewableContribution): self
    {
        if (!$this->reviewableContributions->contains($reviewableContribution)) {
            $this->reviewableContributions[] = $reviewableContribution;
            $reviewableContribution->setApprovedBy($this);
        }

        return $this;
    }

    public function removeReviewableContribution(Contribution $reviewableContribution): self
    {
        if ($this->reviewableContributions->contains($reviewableContribution)) {
            $this->reviewableContributions->removeElement($reviewableContribution);
            // set the owning side to null (unless already changed)
            if ($reviewableContribution->getApprovedBy() === $this) {
                $reviewableContribution->setApprovedBy(null);
            }
        }

        return $this;
    }

    public function isBelongToAFaculty()
    {
        return \in_array($this->getLongRole(), [
            self::ROLE_COORDINATOR,
            self::ROLE_STUDENT,
            self::ROLE_GUEST,
        ], true);
    }

    public function __toString()
    {
        return $this->getFirstName();
    }
}

src/Form/ContributionType.php
<?php

namespace App\Form;

use App\Entity\Contribution;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ContributionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        /** @var Contribution $contribution */
        $contribution = $options['data'] ?? null;
        $isEdit = $contribution && $contribution->getId();

        $builder->add('title');

        if (!$isEdit) {
        } else {
            $builder->add('comment');

//                ->add('commentedAt', null, [
//                    'widget' => 'single_text',
//                ])
        }

//            ->add('publishedAt', null, [
//                'widget' => 'single_text',
//            ])
//            ->add('author')
//            ->add('coordinator')
//            ->add('term')
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Contribution::class,
        ]);
    }
}

templates/contribution/_delete_form.html.twig
<form method="post" action="{{ path('contribution_delete', {'id': contribution.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ contribution.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/contribution/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
<div class="form-group row">
    <div class="col-sm-9">
        <a href="javascript:;" data-toggle="modal" data-target="#terms-and-conditions-modal">
            Terms and Conditions
        </a>
    </div>
</div>
            <button class="btn btn-primary" type="submit">
                <i class="flaticon-edit"></i>
                {{ button_label|default('Save') }}
            </button>
{{ form_end(form) }}

templates/contribution/_item_navigation.html.twig
<div class="row">
    <div class="col-lg-8 col-xl-6 text-left">
        <a class="btn btn-primary m--margin-bottom-10" href="{{ path('contribution_index') }}">back to list</a>
    </div>
    {% if(has_delete) %}
        <div class="col-lg-8 col-xl-6 text-lg-right">
            {{ include('contribution/_delete_form.html.twig') }}
        </div>
    {% endif %}
</div>

templates/contribution/_term_info.html.twig
<div class="m-portlet m-portlet--full-height m-portlet--tabs m--padding-30">
    <h2>Academic Term information</h2>
    <div class="row">
        {% for term in terms %}
            <div class="col-lg-8 col-xl-6">
                {# @var term \App\Entity\Term#}
                <p><strong>{{ term.name }}</strong></p>
                <p>Entry Closure Date: {{ term.entryClosesAt|date('Y-m-d h:i') }}</p>
                <p>Final Closure Date: {{ term.finalClosesAt|date('Y-m-d h:i') }}</p>
                <hr>
            </div>

        {% endfor %}
    </div>
</div>

templates/contribution/edit.html.twig
{% extends 'base.html.twig' %}

{% set breadcrumbs = [{url: '#', text: 'Contribution'}, {text: 'Edit'}] %}

{% block title %}Edit Contribution{% endblock %}
{% block subheader_title %}Edit a contribution{% endblock %}
{% block content %}
    <div class="m-content">
        <div class="m-portlet m-portlet--full-height m-portlet--tabs m--padding-30">
            {{ include('contribution/_item_navigation.html.twig', {'has_delete': true}) }}

            <div class="row">
                <div class="col-lg-8 col-xl-6">
                    {{ include('contribution/_form.html.twig', {'button_label': 'Update'}) }}
                </div>
                <div class="col-sm-4">
                    <h3>Uploaded Word Document</h3>
                    <a target="_blank" download href="{{ uploaded_asset(contribution.documentPath) }}">{{ contribution.documentFilename }}</a>

                    <h3>Images</h3>


                    <div class="row">
                        {% for image in contribution.contributionImages %}
                            <div class="col-md-4">
                                <div class="thumbnail">
                                    <a href="{{ uploaded_asset(image.imagePath) }}">
                                        <img src="{{ uploaded_asset(image.imagePath) }}" alt="{{ image.originalFilename }}"
                                             style="height: 50px; width: auto">
                                        <div class="caption">
                                            <p>{{ image.originalFilename }}</p>
                                        </div>
                                    </a>
                                </div>
                            </div>
                        {% endfor %}

                    </div>

                    <form action="{{ path('contribution_add_image', {
                        id: contribution.id
                    }) }}" method="POST" enctype="multipart/form-data" class="dropzone js-image-dropzone">
                    </form>

                </div>

            </div>
            {{ include('contribution/_terms_and_conditions.html.twig', {'terms': terms}) }}
            {{ include('contribution/_term_info.html.twig', {'terms': terms}) }}

        </div>
    </div>
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/dropzone.css') }}">
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{asset('js/dropzone.js')}}"></script>

    <script>
        Dropzone.autoDiscover = false;

        $(document).ready(function() {
            initializeDropzone();

        })

        function initializeDropzone() {
            var formElement = document.querySelector('.js-image-dropzone');
            if (!formElement) {
                return;
            }

            var dropzone = new Dropzone(formElement, {
                paramName: 'image',
                init: function() {
                    this.on('error', function(file, data) {
                        if (data.detail) {
                            this.emit('error', file, data.detail)
                        }
                    })
                }
            });



        }
    </script>
{% endblock %}

templates/contribution/new.html.twig
{% extends 'base.html.twig' %}

{% set breadcrumbs = [{url: '#', text: 'Contribution'}, {text: 'Edit'}] %}

{% block title %}Create new Contribution{% endblock %}
{% block subheader_title %}Create new Contribution{% endblock %}
{% block content %}
    <div class="m-content">
        <div class="m-portlet m-portlet--full-height m-portlet--tabs m--padding-30">
            {{ include('contribution/_item_navigation.html.twig', {'has_delete': false}) }}
            <div class="row">
                <div class="col-lg-8 col-xl-6">
                    {{ include('contribution/_form.html.twig', {'button_label': 'Create'}) }}
                </div>
            </div>
        </div>
        {{ include('contribution/_terms_and_conditions.html.twig', {'terms': terms}) }}

        {{ include('contribution/_term_info.html.twig', {'terms': terms}) }}

    </div>
{% endblock %}

templates/contribution/publish.html.twig
{% extends 'base.html.twig' %}

{% set breadcrumbs = [{url: '#', text: 'Contribution'}, {text: 'Review'}] %}

{% block title %}Review Contribution{% endblock %}
{% block subheader_title %}Review a contribution{% endblock %}
{% block content %}
    <div class="m-content">
        <div class="m-portlet m-portlet--full-height m-portlet--tabs m--padding-30">
            {{ include('contribution/_item_navigation.html.twig', {'has_delete': false}) }}

            <h3>Uploaded Word Document</h3>
            <a target="_blank" download href="{{ uploaded_asset(contribution.documentPath) }}">{{ contribution.documentFilename }}</a>


            <h3>Images</h3>


            <div class="row">
                {% for image in contribution.contributionImages %}
                    <div class="col-md-4">
                        <div class="thumbnail">
                            <a href="{{ uploaded_asset(image.imagePath) }}">
                                <img src="{{ uploaded_asset(image.imagePath) }}" alt="{{ image.originalFilename }}"
                                     style="height: 50px; width: auto">
                                <div class="caption">
                                    <p>{{ image.originalFilename }}</p>
                                </div>
                            </a>
                        </div>
                    </div>
                {% endfor %}

            </div>

            <div class="row">
                <div class="col-lg-8 col-xl-6">
                    {{ include('contribution/_form.html.twig', {'button_label': 'Publish Review'}) }}
                </div>
            </div>
        </div>
        {{ include('contribution/_term_info.html.twig', {'terms': terms}) }}

    </div>
{% endblock %}

templates/contribution/review.html.twig
{% extends 'base.html.twig' %}

{% set breadcrumbs = [{url: '#', text: 'Contribution'}, {text: 'Review'}] %}

{% block title %}Review Contribution{% endblock %}
{% block subheader_title %}Review a contribution{% endblock %}
{% block content %}
    <div class="m-content">
        <div class="m-portlet m-portlet--full-height m-portlet--tabs m--padding-30">
            {{ include('contribution/_item_navigation.html.twig', {'has_delete': false}) }}

            <h3>Uploaded Word Document</h3>
            <a target="_blank" download href="{{ uploaded_asset(contribution.documentPath) }}">
                {{ contribution.documentFilename }}
            </a>


            <h3>Images</h3>


            <div class="row">
                {% for image in contribution.contributionImages %}
                    <div class="col-md-4">
                        <div class="thumbnail">
                            <a href="{{ uploaded_asset(image.imagePath) }}">
                                <img src="{{ uploaded_asset(image.imagePath) }}" alt="{{ image.originalFilename }}"
                                     style="height: 50px; width: auto">
                                <div class="caption">
                                    <p>{{ image.originalFilename }}</p>
                                </div>
                            </a>
                        </div>
                    </div>
                {% endfor %}

            </div>

            <div class="row">
                <div class="col-lg-8 col-xl-6">
                    {{ include('contribution/_form.html.twig', {'button_label': 'Update Review'}) }}
                </div>
            </div>


        </div>
        {{ include('contribution/_term_info.html.twig', {'terms': terms}) }}

    </div>
{% endblock %}

templates/contribution/show.html.twig
{% extends 'base.html.twig' %}

{% set breadcrumbs = [{url: '#', text: 'Contribution'}, {text: 'Detail'}] %}

{% block title %}Contribution{% endblock %}
{% block subheader_title %}contribution{% endblock %}
{% block content %}


    <div class="m-content">
        <div class="m-portlet m-portlet--full-height m-portlet--tabs m--padding-30">
            {{ include('contribution/_item_navigation.html.twig', {'has_delete': app.user.longRole == 'ROLE_STUDENT'}) }}
            <table class="table">
                <tbody>
                <tr>
                    <th>Id</th>
                    <td>{{ contribution.id }}</td>
                </tr>
                <tr>
                    <th>Title</th>
                    <td>{{ contribution.title }}</td>
                </tr>
                <tr>
                    <th>Word Document</th>
                    <td><a target="_blank" download href="{{ uploaded_asset(contribution.documentPath) }}">{{ contribution.documentFilename }}</a></td>
                </tr>
                <tr>
                    <th>Images</th>
                    <td>
                        {% for image in contribution.contributionImages %}
                            <a target="_blank" download href="{{ uploaded_asset(image.imagePath) }}">
                                <img src="{{ uploaded_asset(image.imagePath) }}" alt="" style="height: 50px; width: auto">
                                {{ image.originalFilename }}
                            </a>
                        {% endfor %}
                    </td>
                </tr>
                <tr>
                    <th>Author</th>
                    <td>{{ contribution.author }}</td>
                </tr>
                <tr>
                    <th>Coordinator</th>
                    <td>{{ contribution.approvedBy }}</td>
                </tr>
                <tr>
                    <th>Student Comment</th>
                    <td>{{ contribution.comment }}</td>
                </tr>
                <tr>
                    <th>Coordinator Feedback</th>
                    <td>{{ contribution.feedback }}</td>
                </tr>

                {% if contribution.approvedAt %}
                    <tr>
                        <th>Approved At</th>
                        <td> {{ contribution.approvedAt ? contribution.approvedAt|date('Y-m-d H:i:s') : ''}} </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="2"> <span class="text-warning">Waiting for approval</span></td>
                    </tr>
                {% endif %}

                {% if contribution.publishedAt %}
                    <tr>
                        <th>Published At</th>
                        <td> {{ contribution.publishedAt ? contribution.publishedAt|date('Y-m-d H:i:s') : ''}} </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="2"> <span class="text-warning">Unpublished</span></td>
                    </tr>
                {% endif %}


                </tbody>
            </table>
        </div>
    </div>
{% endblock %}