src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface
{
    const ROLE_ADMIN = 'ROLE_ADMIN';
    const ROLE_MANAGER = 'ROLE_MANAGER';
    const ROLE_COORDINATOR = 'ROLE_COORDINATOR';
    const ROLE_STUDENT = 'ROLE_STUDENT';
    const ROLE_GUEST = 'ROLE_GUEST';

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @var string
     */
    private $plainPassword;

    /**
     * @var bool
     * @ORM\Column(type="boolean")
     */
    private $enabled;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lastName;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Faculty", inversedBy="users")
     */
    private $faculty;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Contribution", mappedBy="author", orphanRemoval=true)
     */
    private $contributions;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Contribution", mappedBy="coordinator")
     */
    private $reviewableContributions;

    public function __construct()
    {
        $this->contributions = new ArrayCollection();
        $this->reviewableContributions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        $this->plainPassword = null;
    }

    /**
     * @return string
     */
    public function getPlainPassword(): ?string
    {
        return $this->plainPassword;
    }

    /**
     * @param string $plainPassword
     */
    public function setPlainPassword(?string $plainPassword): void
    {
        $this->plainPassword = $plainPassword;
    }

    /**
     * @return bool
     */
    public function isEnabled(): bool
    {
        return $this->enabled;
    }

    /**
     * @param bool $enabled
     */
    public function setEnabled(bool $enabled): void
    {
        $this->enabled = $enabled;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(?string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(?string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getDisplayName(): string
    {
        return (!$this->firstName && !$this->lastName) ? $this->email : "$this->firstName $this->lastName";
    }

    public function getFaculty(): ?Faculty
    {
        return $this->faculty;
    }

    public function setFaculty(?Faculty $faculty): self
    {
        $this->faculty = $faculty;

        return $this;
    }

    public function getShortRole(): string
    {
        return mb_strtolower(str_replace('ROLE_', '', $this->roles[0]));
    }

    public function getLongRole(): string
    {
        return $this->roles[0];
    }

    /**
     * @return Collection|Contribution[]
     */
    public function getContributions(): Collection
    {
        return $this->contributions;
    }

    public function addContribution(Contribution $contribution): self
    {
        if (!$this->contributions->contains($contribution)) {
            $this->contributions[] = $contribution;
            $contribution->setAuthor($this);
        }

        return $this;
    }

    public function removeContribution(Contribution $contribution): self
    {
        if ($this->contributions->contains($contribution)) {
            $this->contributions->removeElement($contribution);
            // set the owning side to null (unless already changed)
            if ($contribution->getAuthor() === $this) {
                $contribution->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Contribution[]
     */
    public function getReviewableContributions(): Collection
    {
        return $this->reviewableContributions;
    }

    public function addReviewableContribution(Contribution $reviewableContribution): self
    {
        if (!$this->reviewableContributions->contains($reviewableContribution)) {
            $this->reviewableContributions[] = $reviewableContribution;
            $reviewableContribution->setApprovedBy($this);
        }

        return $this;
    }

    public function removeReviewableContribution(Contribution $reviewableContribution): self
    {
        if ($this->reviewableContributions->contains($reviewableContribution)) {
            $this->reviewableContributions->removeElement($reviewableContribution);
            // set the owning side to null (unless already changed)
            if ($reviewableContribution->getApprovedBy() === $this) {
                $reviewableContribution->setApprovedBy(null);
            }
        }

        return $this;
    }

    public function isBelongToAFaculty()
    {
        return \in_array($this->getLongRole(), [
            self::ROLE_COORDINATOR,
            self::ROLE_STUDENT,
            self::ROLE_GUEST,
        ], true);
    }

    public function __toString()
    {
        return $this->getFirstName();
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Article Hub - {% block title %}{% endblock %}</title>
    <link rel="shortcut icon" href="{{ asset('images/favicon.ico') }}" type="image/x-icon">

    <!--begin::Web font -->
    <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.16/webfont.js"></script>
    <script>
        WebFont.load({
            google: {"families": ["Poppins:300,400,500,600,700", "Roboto:300,400,500,600,700"]},
            active: function () {
                sessionStorage.fonts = true;
            }
        });
    </script>

    <!--end::Web font -->
    {% block stylesheets %}
        <!--begin::Global Theme Styles -->
        <link href="{{ asset('css/vendors.bundle.css') }}" rel="stylesheet" type="text/css" />

        <!--RTL version:<link href="assets/vendors/base/vendors.bundle.rtl.css" rel="stylesheet" type="text/css" />-->
        <link href="{{ asset('css/style.bundle.css') }}" rel="stylesheet" type="text/css" />

        <!--RTL version:<link href="assets/demo/default/base/style.bundle.rtl.css" rel="stylesheet" type="text/css" />-->

        <!--end::Global Theme Styles -->

        <!--begin::Page Vendors Styles -->
    {% endblock %}
</head>
<body class="m-page--fluid m--skin- m-content--skin-light2 m-header--fixed m-header--fixed-mobile m-aside-left--enabled m-aside-left--skin-dark m-aside-left--fixed m-aside-left--offcanvas m-footer--push m-aside--offcanvas-default {% block body_class %}{% endblock %}">
{% block body %}
    <!-- begin:: Page -->
    <div class="m-grid m-grid--hor m-grid--root m-page">
        <!-- BEGIN: Header -->
        {% include 'header.html.twig' %}
        <!-- END: Header -->

        <!-- begin::Body -->
        <div class="m-grid__item m-grid__item--fluid m-grid m-grid--ver-desktop m-grid--desktop m-body">

            <!-- BEGIN: Left Aside -->
            <button class="m-aside-left-close  m-aside-left-close--skin-dark " id="m_aside_left_close_btn"><i
                        class="la la-close"></i></button>
            <div id="m_aside_left" class="m-grid__item	m-aside-left  m-aside-left--skin-dark ">

                <!-- BEGIN: Aside Menu -->
                <div id="m_ver_menu" class="m-aside-menu  m-aside-menu--skin-dark m-aside-menu--submenu-skin-dark "
                     m-menu-vertical="1" m-menu-scrollable="1" m-menu-dropdown-timeout="500"
                     style="position: relative;">

                        <ul class="m-menu__nav  m-menu__nav--dropdown-submenu-arrow ">
                            <li class="m-menu__section ">
                                <h4 class="m-menu__section-text">Components</h4>
                                <i class="m-menu__section-icon flaticon-more-v2"></i>
                            </li>
                            <li class="m-menu__item  m-menu__item--submenu"><a href="{{ path('default') }}" class="m-menu__link"><i
                                            class="m-menu__link-icon la la-building"></i><span class="m-menu__link-text">Statistics</span></a>
                            </li>
                            <li class="m-menu__item  m-menu__item--submenu"><a href="{{ path('contribution_index') }}" class="m-menu__link"><i
                                            class="m-menu__link-icon fa fa-book"></i><span class="m-menu__link-text">Contributions</span></a>
                            </li>

                            {% if is_granted('ROLE_ADMIN') %}
                                <li class="m-menu__item  m-menu__item--submenu"><a href="{{ path('user_index') }}" class="m-menu__link"><i
                                                class="m-menu__link-icon flaticon-user"></i><span
                                                class="m-menu__link-text">User</span></a>
                                </li>
                                <li class="m-menu__item  m-menu__item--submenu"><a href="{{ path('faculty_index') }}" class="m-menu__link"><i
                                                class="m-menu__link-icon la la-building"></i><span class="m-menu__link-text">Faculties</span></a>
                                </li>
                                <li class="m-menu__item  m-menu__item--submenu"><a href="{{ path('term_index') }}" class="m-menu__link"><i
                                                class="m-menu__link-icon la la-building"></i><span class="m-menu__link-text">Terms</span></a>
                                </li>
                            {% endif %}
                        </ul>
                </div>

                <!-- END: Aside Menu -->
            </div>

            <!-- END: Left Aside -->
            {% block body_wrapper %}
                <div class="m-grid__item m-grid__item--fluid m-wrapper">

                    <!-- BEGIN: Subheader -->
                    {% block subheader %}
                        <div class="m-subheader ">
                            <div class="d-flex align-items-center">
                                <div class="mr-auto">
                                    <h3 class="m-subheader__title m-subheader__title--separator">{% block subheader_title %}{% endblock %}</h3>
                                    {% block subheader_breadcrumbs %}
                                        <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                                            <li class="m-nav__item m-nav__item--home">
                                                <a href="/" class="m-nav__link m-nav__link--icon">
                                                    <i class="m-nav__link-icon la la-home m--margin-left-5"></i>
                                                </a>
                                            </li>
                                            {% if breadcrumbs is defined %}
                                                {% for item in breadcrumbs %}
                                                    <li class="m-nav__separator">-</li>
                                                    <li class="m-nav__item">
                                                        {% if item.url is defined %}
                                                            <a href="{{ item.url }}" class="m-nav__link">
                                                                <span class="m-nav__link-text">{{ item.text }}</span>
                                                            </a>
                                                        {% else %}
                                                            <span class="m-nav__link-text">{{ item.text }}</span>
                                                        {% endif %}
                                                    </li>
                                                {% endfor %}
                                            {% endif %}
                                        </ul>
                                    {% endblock %}
                                </div>
                                {% block subheader_actions %}
                                    {% if quick_actions is defined %}
                                        <div class="m-dropdown m-dropdown--inline m-dropdown--arrow m-dropdown--align-right m-dropdown--align-push"
                                             m-dropdown-toggle="hover" aria-expanded="true">
                                            <a href="#"
                                               class="m-portlet__nav-link btn btn-lg btn-secondary  m-btn m-btn--outline-2x m-btn--air m-btn--icon m-btn--icon-only m-btn--pill  m-dropdown__toggle">
                                                <i class="la la-plus m--hide"></i>
                                                <i class="la la-ellipsis-h"></i>
                                            </a>
                                            <div class="m-dropdown__wrapper">
                                                <span class="m-dropdown__arrow m-dropdown__arrow--right m-dropdown__arrow--adjust"></span>
                                                <div class="m-dropdown__inner">
                                                    <div class="m-dropdown__body">
                                                        <div class="m-dropdown__content">
                                                            <ul class="m-nav">
                                                                <li class="m-nav__section m-nav__section--first m--hide">
                                                                    <span class="m-nav__section-text">Quick Actions</span>
                                                                </li>
                                                                {% for item in quick_actions %}
                                                                    <li class="m-nav__item">
                                                                        {% if item.url is defined %}
                                                                            <a href="{{ item.url }}" class="m-nav__link">
                                                                                <i class="m-nav__link-icon {{ item.icon }}"></i>
                                                                                <span class="m-nav__link-text">{{ item.text }}</span>
                                                                            </a>
                                                                        {% else %}
                                                                            <div class="m-nav__link">
                                                                                <i class="m-nav__link-icon {{ item.icon }}"></i>
                                                                                <span class="m-nav__link-text">{{ item.text }}</span>
                                                                            </div>
                                                                        {% endif %}
                                                                    </li>
                                                                {% endfor %}
                                                            </ul>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    {% endif %}
                                {% endblock %}
                            </div>
                        </div>
                    {% endblock %}

                    <!-- END: Subheader -->
                    <!-- begin::Flash messages -->
                    {% for label, messages in app.flashes(['success', 'error', 'warning']) %}
                        {% for message in messages %}
                            <div class="row">
                                <div class="col-xl-6">
                                    <div class="m--margin-5 alert {% if label == 'error' %} alert-danger {% else %} alert-{{ label }} {% endif %} flash-message" data-flash-type="{{ label }}">
                                        {{ message }}
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    {% endfor %}
                    <!-- end::Flash messages -->
                    {% block content %}

                    {% endblock %}
                </div>
            {% endblock %}
        </div>

        <!-- end:: Body -->
    </div>

    <!-- end:: Page -->

    <!-- begin::Scroll Top -->
    <div id="m_scroll_top" class="m-scroll-top">
        <i class="la la-arrow-up"></i>
    </div>

    <!-- end::Scroll Top -->


{% endblock %}
{% block javascripts %}
    <!-- begin::Quick Nav -->

    <!--begin::Global Theme Bundle -->
    <script src="{{asset('js/vendors.bundle.js')}}" type="text/javascript"></script>
    <script src="{{asset('js/scripts.bundle.js')}}" type="text/javascript"></script>


    <script src="{{asset('js/flot.bundle.js')}}" type="text/javascript"></script>

    <!--end::Global Theme Bundle -->

    <!--begin::Page Vendors -->

    <!--end::Page Vendors -->

    <!--begin::Page Scripts -->
    <script src="{{asset('js/dashboard.js')}}" type="text/javascript"></script>



    <!--end::Page Scripts -->
{% endblock %}
</body>
</html>

templates/form.html.twig
{% use "bootstrap_4_horizontal_layout.html.twig" %}

{% block form_label_errors %}{% endblock form_label_errors %}

{% block form_row -%}
    {%- if expanded is defined and expanded -%}
        {{ block('fieldset_form_row') }}
    {%- else -%}
        {%- set widget_attr = {} -%}
        {%- if help is not empty -%}
            {%- set widget_attr = {attr: {'aria-describedby': id ~"_help"}} -%}
        {%- endif -%}
        <div class="form-group row{% if (not compound or force_error|default(false)) and not valid %} is-invalid{% endif %}">
            {{- form_label(form) -}}
            <div class="{{ block('form_group_class') }}">
                {{- form_widget(form, widget_attr) -}}
                {%- if errors|length > 0 -%}
                    <div class="form-control-feedback">
                        {{- form_errors(form) -}}
                    </div>
                {%- endif -%}
                {{- form_help(form) -}}
            </div>
            {##}</div>
    {%- endif -%}
{%- endblock form_row %}

{% block form_label_class -%}
    col-sm-3
{%- endblock form_label_class %}

{% block form_group_class -%}
    col-sm-9
{%- endblock form_group_class %}

templates/header.html.twig
<header id="m_header" class="m-grid__item    m-header " m-minimize-offset="200" m-minimize-mobile-offset="200">
    {% if is_granted('ROLE_PREVIOUS_ADMIN') %}
        <a href="{{ path('default', {'_switch_user': '_exit'}) }}">Exit impersonation</a>
    {% endif %}
    <div class="m-container m-container--fluid m-container--full-height">
        <div class="m-stack m-stack--ver m-stack--desktop">
            <!-- BEGIN: Brand -->
            <div class="m-stack__item m-brand  m-brand--skin-dark ">
                <div class="m-stack m-stack--ver m-stack--general">
                    <div class="m-stack__item m-stack__item--middle m-brand__logo">
                        <a href="/" class="m-brand__logo-wrapper">
                            <img alt="" src="{{ asset('images/logo.png') }}" style="height: 60px" />
                        </a>
                    </div>
                    <div class="m-stack__item m-stack__item--middle m-brand__tools">

                        <!-- BEGIN: Left Aside Minimize Toggle -->
                        <a href="javascript:;" id="m_aside_left_minimize_toggle" class="m-brand__icon m-brand__toggler m-brand__toggler--left m--visible-desktop-inline-block  ">
                            <span></span>
                        </a>

                        <!-- END -->

                        <!-- BEGIN: Responsive Aside Left Menu Toggler -->
                        <a href="javascript:;" id="m_aside_left_offcanvas_toggle" class="m-brand__icon m-brand__toggler m-brand__toggler--left m--visible-tablet-and-mobile-inline-block">
                            <span></span>
                        </a>

                        <!-- END -->

                        <!-- BEGIN: Responsive Header Menu Toggler -->
                        <a id="m_aside_header_menu_mobile_toggle" href="javascript:;" class="m-brand__icon m-brand__toggler m--visible-tablet-and-mobile-inline-block">
                            <span></span>
                        </a>

                        <!-- END -->

                        <!-- BEGIN: Topbar Toggler -->
                        <a id="m_aside_header_topbar_mobile_toggle" href="javascript:;" class="m-brand__icon m--visible-tablet-and-mobile-inline-block">
                            <i class="flaticon-more"></i>
                        </a>

                        <!-- BEGIN: Topbar Toggler -->
                    </div>
                </div>
            </div>

            <!-- END: Brand -->
            <div class="m-stack__item m-stack__item--fluid m-header-head" id="m_header_nav">

                <!-- BEGIN: Horizontal Menu -->
                <button class="m-aside-header-menu-mobile-close  m-aside-header-menu-mobile-close--skin-dark " id="m_aside_header_menu_mobile_close_btn"><i class="la la-close"></i></button>
                <div id="m_header_menu" class="m-header-menu m-aside-header-menu-mobile m-aside-header-menu-mobile--offcanvas  m-header-menu--skin-light m-header-menu--submenu-skin-light m-aside-header-menu-mobile--skin-dark m-aside-header-menu-mobile--submenu-skin-dark ">
                    <ul class="m-menu__nav  m-menu__nav--submenu-arrow ">
                        <li class="m-menu__item  m-menu__item--submenu m-menu__item--rel"><a href="{{ path('contribution_index') }}" class="m-menu__link" title="List of contributions"><span
                                        class="m-menu__link-text">Contributions</span></a>
                        </li>
                        <li class="m-menu__item  m-menu__item--submenu m-menu__item--rel"><a href="{{ path('default') }}" class="m-menu__link" title="Statistic"><span
                                        class="m-menu__link-text">Statistic</span></a>
                        </li>
                    </ul>
                </div>

                <!-- END: Horizontal Menu -->

                <!-- BEGIN: Topbar -->
                <div id="m_header_topbar" class="m-topbar  m-stack m-stack--ver m-stack--general m-stack--fluid">
                    <div class="m-stack__item m-topbar__nav-wrapper">
                        <ul class="m-topbar__nav m-nav m-nav--inline">
                            <li class="m-nav__item m-topbar__user-profile m-topbar__user-profile--img  m-dropdown m-dropdown--medium m-dropdown--arrow m-dropdown--header-bg-fill m-dropdown--align-right m-dropdown--mobile-full-width m-dropdown--skin-light"
                                m-dropdown-toggle="click">
                                <a href="#" class="m-nav__link m-dropdown__toggle">
                                    <span class="m-topbar__welcome">{{ app.user.displayName }}</span><br>
                                    <span class="m-topbar__welcome text-info">{{ app.user.shortRole }}</span>
                                </a>
                                <div class="m-dropdown__wrapper">
                                    <span class="m-dropdown__arrow m-dropdown__arrow--right m-dropdown__arrow--adjust"></span>
                                    <div class="m-dropdown__inner">
                                        <div class="m-dropdown__header m--align-center" style="background: url({{ asset('images/user_profile_bg.jpg') }}); background-size: cover;">
                                            <div class="m-card-user m-card-user--skin-dark">
                                                <div class="m-card-user__pic">
                                                    {#<img src="assets/app/media/img/users/user4.jpg" class="m--img-rounded m--marginless" alt="" />#}


                                                    <span class="m-type m-type--lg m--bg-danger"><span class="m--font-light">{{ app.user.displayName | first | upper }}</span></span>

                                                </div>
                                                <div class="m-card-user__details">
                                                    <span class="m-card-user__name m--font-weight-500">{{ app.user.firstName }} {{ app.user.lastName }}</span>
                                                    <a href="#" class="m-card-user__email m--font-weight-300 m-link">{{ app.user.email }}</a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="m-dropdown__body">
                                            <div class="m-dropdown__content">
                                                <ul class="m-nav m-nav--skin-light">
                                                    <li class="m-nav__section m--hide">
                                                        <span class="m-nav__section-text">Section</span>
                                                    </li>
                                                    <li class="m-nav__item">
                                                        <a href="{{ path('profile') }}" class="m-nav__link">
                                                            <i class="m-nav__link-icon flaticon-profile-1"></i>
                                                            <span class="m-nav__link-title">
																			<span class="m-nav__link-wrap">
																				<span class="m-nav__link-text">My Profile</span>
																			</span>
																		</span>
                                                        </a>
                                                    </li>
                                                    <li class="m-nav__item">
                                                        <a href="{{ path('profile_change_password') }}" class="m-nav__link">
                                                            <i class="m-nav__link-icon flaticon-lifebuoy"></i>
                                                            <span class="m-nav__link-text">Change Password</span>
                                                        </a>
                                                    </li>
                                                    <li class="m-nav__separator m-nav__separator--fit">
                                                    </li>
                                                    <li class="m-nav__item">
                                                        <a href="{{ path('app_logout') }}" class="btn m-btn--pill    btn-secondary m-btn m-btn--custom m-btn--label-brand m-btn--bolder">Logout</a>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>

                <!-- END: Topbar -->
            </div>
        </div>
    </div>
</header>